# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
a=np.array([int(input()) for i in range(5)])
b=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((a,b))))

1
2
3
4
5
6
7
8
9
10
[ 1  2  3  4  5  6  7  8  9 10]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [5]:
arr=np.array([1,2,3,4,5,6])
print(arr.ndim)
print(arr.size)

1
6


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [6]:
arr=np.array([1,2,3,4,5,6])
t=arr
t=t[:, np.newaxis]
print(t)
print(arr)
t=arr
t=np.expand_dims(t,2)
print(t)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


C:\Users\CH SHANMUKH CHOWDARY\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  import sys


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.vstack(a))
print(np.hstack(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


# Questions 6:
How to get unique items and counts of unique items?

<h2>np.unique function can be used to get the unique items.
By passing the argument return_counts=True argument along with the array return the unique items and their counts</h2>

In [10]:
a=np.arange(1,10)
print(np.unique(a,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))
